language: cpp

matrix:
 include:
  - os: linux
    dist: trusty
    sudo: required
    compiler: gcc
    env:
     - QT_BASE=59
#  - os: linux
#    dist: trusty
#    sudo: required
#    compiler: gcc
#    env:
#     - QT_BASE=59 USE_CMAKE=true
  - os: osx
    compiler: clang
    env:
     - QT_BASE=59
#  - os: osx
#    compiler: clang
#    env:
#     - QT_BASE=59 USE_CMAKE=true

before_install:
  - if [[ "$QT_BASE" = "59" && "$TRAVIS_OS_NAME" = "linux" ]]; then sudo add-apt-repository ppa:beineri/opt-qt59-trusty -y; fi
  - if [ "$TRAVIS_OS_NAME" = "linux" ]; then
      sudo apt-get update -qq;
    else
      brew update;
    fi

install:
  - if [ "$QT_BASE" = "59" ]; then
      if [ "$TRAVIS_OS_NAME" = "linux" ]; then
        sudo apt-get install -qq qt59base; source /opt/qt59/bin/qt59-env.sh;
      else
        brew install qt5;
        brew link --force qt5;
        export HOMEBREW_QT5_VERSION=$(brew list --versions qt5 | rev | cut -d' ' -f1 | rev);
        ln -s /usr/local/Cellar/qt5/$HOMEBREW_QT5_VERSION/mkspecs /usr/local/mkspecs;
      fi
    fi

script:
  # build library and tests, install library
  - mkdir ./build && cd ./build
  - if [ "$USE_CMAKE" = "true" ]; then
      cmake --version;
      cmake -DCMAKE_BUILD_TYPE=Release ..;
      make;
    else
      qmake -v;
      qmake ../DisMo.pro CONFIG+=release;
      make;
    fi

notifications:
  email: false
